activation: complex_tanh
init_method: structured_preserve
in_features: 64
hidden_size: 128
n_layers: 200
epochs: 50
batch_size: 128
device: cpu
monitor_layers:
- 10
- 19
dataset_name: mnist
dataset_root: data
output_dir: single_experiment_results

out_features: 10